### PR TITLE
Add content guard.

### PR DESCRIPTION
**Pull request by jortel**
https://pulp.plan.io/issues/4009

Initially reviewed in PR #2 but needed another PR when `master` got reset as part of repository setup.

### CODE REVIEW

**Comment by jortel** [comment]
@bmbouter: The only outstanding requested change is the content guard raising `HTTPForbidden` instead of `PermissionError`.  The original design specifies that the content guard raise `PermisisonError` with a description of the reason the request was denied.  The content app (originally) caught the `PermissionError`, logged it with contextual information that included:
- The content guard name.
- The path component of the URL
- The reason denied by the content guard.
Then raised the 403.

The `aiohttp.web_exceptions.HTTPForbidden` exception does not take parameters so raising it instead of `PermissionError` requires that the plugin writer log (with context) all error or denials.  Leaving it as is and fixing the content app seems simpler for plugin writers.

see: pulp/pulp#3833

**Comment by bmbouter** [comment]
@jortel this argument is totally convincing. I can see `PermissionError` keeps these things separate and that is a good thing in this situation.

If that's the case do you think the `PermissionError` should be caught [here](https://github.com/pulp/pulp/blob/master/pulpcore/content/handler.py#L161) and transformed to the `HTTPForbidden` so that the response code to the user is 403?

**Comment by jortel** [comment]
> @jortel this argument is totally convincing. I can see `PermissionError` keeps these things separate and that is a good thing in this situation.
> 
> If that's the case do you think the `PermissionError` should be caught [here](https://github.com/pulp/pulp/blob/master/pulpcore/content/handler.py#L161) and transformed to the `HTTPForbidden` so that the response code to the user is 403?

No, I think it should be dealt with as proposed here: pulp/pulp#3833

**Comment by bmbouter** [comment]
> No, I think it should be dealt with as proposed here: [pulp/pulp#3833](https://github.com/pulp/pulp/pull/3833)

That sounds great.

**Pull request merged**
