### PR TITLE
Adding travis scripts and fixing folder structure for tests

### PR DESCRIPTION
**Pull request by rochacbruno**
- adding all travis machinery/scripts
- moving structure to comply with plugin template
- adding missing [postgres] estra requires
- QE owns functional tests
- Fixed some PEP8 issues

Should QE own `.travis*` ?

### CODE REVIEW

**Comment by rochacbruno** [comment]
I dont know how to fix the travis error

**Comment by rochacbruno** [comment]
@dkliban @jortel @pulp/qe 

I dont know the reason travis is failing (error starting resource-manager)

If any of you know how to fix that Add more commits by pushing to the add_travis branch on rochacbruno/pulp-certguard.

**Comment by kersommoura** [comment]
@rochacbruno, QE should be the owner of functional tests.

**Comment by rochacbruno** [comment]
@dkliban @kersommoura all tests passed, Travis is in place

**Pull request merged**
