### PR TITLE
Fix openapi naming issue in tests.

### PR DESCRIPTION
**Pull request by ggainey**
[noissue]

### CODE REVIEW

**Comment by bmbouter** [comment]
Do we know why the names changed? I'm just curious.

**Comment by ggainey** [comment]
> Do we know why the names changed? I'm just curious.

I don't, altho I suspect an openapi Thing, since these are generated names. It's been breaking CI for the last 19 days :(

**Review by bmbouter — APPROVED** [review]
Thanks!

**Comment by ggainey** [comment]
The tests aren't broken - pulpcore is. Closing this PR.

**Pull request closed without merging**
